export const CREATE__MEETING = 'CREATE__MEETING',
    EDIT_MEETING = 'EDIT_MEETING',
    CHANGE_DATE = 'CHANGE_DATE',
    CHOOSE_DATE_ON_INPUT = 'CHOOSE_DATE_ON_INPUT',
    SHOW_MAIN = 'SHOW_MAIN',
    CONFIRMED_DELETE = 'CONFIRMED_DELETE',
    UNCONFIRMED_DELETE = 'UNCONFIRMED_DELETE';